<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMgdUBaS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMgdUBaS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMgdUBaS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMgdUBaS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMgdUBaS\App_KernelDevDebugContainer([
    'container.build_hash' => 'MgdUBaS',
    'container.build_id' => 'c2490d31',
    'container.build_time' => 1680886816,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMgdUBaS');
